name: deploy-cloudrun Unit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  my-cicd-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      # Get ID token
      - name: get ID token
        run: |
          big_json=$(curl -s -X POST -H "Content-Type:application/x-www-form-urlencoded" -d 'grant_type=password&client_id=ghactions&username=demorepo&password=HelloWorld123#&scope=openid&client_secret=HelloWorld123#' 'https://ghactionsoidc.azurewebsites.net/connect/token/')
          big_json="${big_json//'%'/'%25'}"
          big_json="${big_json//$'\n'/'%0A'}"
          big_json="${big_json//$'\r'/'%0D'}"
          echo "::set-output name=big_json::$big_json"
        id: tokenid
      
      # Get credentials
      - name: get Access Token
        run: |
          big_json=$(curl -s -X POST --header 'Content-Type: application/json' --data-raw '{"audience": "//iam.googleapis.com/projects/274737558741/locations/global/workloadIdentityPools/arwinderidpool/providers/gh-idprovider","grantType": "urn:ietf:params:oauth:grant-type:token-exchange","requestedTokenType": "urn:ietf:params:oauth:token-type:access_token","scope": "https://www.googleapis.com/auth/cloud-platform","subjectTokenType": "urn:ietf:params:oauth:token-type:jwt","subjectToken": "${{fromJson(steps.tokenid.outputs.big_json).id_token}}"}' 'https://sts.googleapis.com/v1beta/token')
          big_json="${big_json//'%'/'%25'}"
          big_json="${big_json//$'\n'/'%0A'}"
          big_json="${big_json//$'\r'/'%0D'}"
          echo "::set-output name=big_json::$big_json"
        id: accessToken
        
      - name: print stuff
        run: echo '${{steps.accessToken.outputs.big_json}}'
        
